name: Build Docker Image Dagster locally

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (local only)
        uses: docker/build-push-action@v5
        with:
          context: ./quickstart
          file: ./quickstart/Dockerfile
          push: false  # Build locally only on GitHub runner
          tags: local/dagster_quickstart:latest
